config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :admins
  devise_for :users

  get 'admins/dashboard' => 'dashboard#index', as: :dashboard

  resources :products

  get 'add_to_cart' => 'carts#create', as: :add_to_cart
  get 'users/cart' => 'carts#show', as: :show_cart
  get 'cart/remove_item' => 'carts#remove_item', as: :remove_item
  get 'users/:id/orders/new' => 'orders#new', as: :new_order
  get 'users/:id/orders/create' => 'orders#create', as: :order_confirmation
  get 'users/:id/orders/display' => 'orders#show', as: :order_summary

  get 'fetch_products' => 'home#load_products'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.order("created_at DESC").limit(6)
    @last_dt = @products.any? ? @products.last.created_at : ''
    @load_more = Product.all.count > 6
  end

  def load_products
    sleep 1
    last = if params[:last_dt].blank?
      Time.now + 1.second
    else
      ActiveSupport::TimeZone['UTC'].parse(params[:last_dt])
    end

    @products = Product.where("created_at < ?", last).order("created_at DESC").limit(6)
    @last_dt = @products.empty? ? false : @products.last.created_at
  end
end

app/views/home/_product.html.erb
<div class="product col-md-3" id="product-<%= product.id %>">
  <div class="prd_lnks">
    <% if admin_signed_in? %>
      <%= link_to "Edit", edit_product_path(product) %> |
      <%= link_to "Delete", product, method: :delete, confirm: "Are you sure?" %>
    <% else %>
      <% if product.quantity > 0 %>
        <%= link_to "Add to cart", add_to_cart_path(product_id: product.id) %>
      <% else %>
        <label>Out of stock</label>
      <% end %>
    <% end %>
  </div>

  <div class="product_attribute row">
    <h4><%= link_to product.name, product_path(product) %></h4>
  </div>

  <div class="row">
    <div class="product_attribute row">
      <div class="col-lg-10" style="overflow: hidden;">
        <div><%= truncate(product.description, length: 180) %></div>
      </div>
    </div><br />

    <div class="row">
      <div class="col-lg-2"><b>Price</b></div>
      <div class="col-lg-10"><%= number_with_delimiter(product.price, locale: :en) %> INR</div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if @load_more %>
  <%= javascript_tag do %>
    window.fetchMore = true;
  <% end %>
<% end %>

<h3>Available Products</h3>

<div class="products_grid row" data="<%= @last_dt %>">
  <%= render partial: "product", collection: @products, as: :product %>
</div>

<div id="loading_txt">
  Loading ...
</div>

app/views/home/load_products.js.erb
<% if @products.any? %>
	$('.products_grid').append('<%= j render(partial: "product", collection: @products, as: :product) %>');
	$('.products_grid').attr("data", "<%= @last_dt %>");
<% else %>
	window.fetchMore = false;
<% end %>