config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :admins
  devise_for :users

  get 'admins/dashboard' => 'dashboard#index', as: :dashboard

  resources :products

  get 'add_to_cart' => 'carts#create', as: :add_to_cart
  get 'users/cart' => 'carts#show', as: :show_cart
  get 'cart/remove_item' => 'carts#remove_item', as: :remove_item
  get 'users/:id/orders/new' => 'orders#new', as: :new_order
  get 'users/:id/orders/create' => 'orders#create', as: :order_confirmation
  get 'users/:id/orders/display' => 'orders#show', as: :order_summary

  get 'fetch_products' => 'home#load_products'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :items, as: :itemable, dependent: :destroy, autosave: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :authenticate_user!, only: [:show]

  def show
    @products = []

    if user_signed_in?
      @products = ProductService.new({}).fetch_cart_products(current_user)
    else
      @products = ProductService.new({}).fetch_session_cart_products(session[:cart]['products'])
    end
  end

  def create
    ## create session for cart, if does not exists
    session[:cart] ||= {}
    products = session[:cart]['products']

    ## if exists, add new, else create new variable
    if products.present?
      session[:cart]['products'] << params[:product_id]
    else
      session[:cart]['products'] = Array(params[:product_id])
    end

    res = true
    if user_signed_in?
      ## persist to DB
      res = CartService.new(current_user, session[:cart]).create_or_update_cart
    end

    if res
      flash[:success] = 'Product successfully added to cart!'
    else
      flash[:alert] = 'Unable to add to cart. Please try again in sometime.'
    end

    flash.keep
    redirect_to request.referer
  end

  def remove_item
    product_id = params[:product_id]
    session[:cart]['products'].delete product_id

    res = true
    if user_signed_in?
      ## remove from DB
      session_hash = { cart: { 'products' => [product_id] } }
      res = CartService.new(current_user, session_hash[:cart]).remove_cart_item
    end

    if res
      flash[:success] = 'Item removed from cart!'
    else
      flash[:alert] = 'Unable to remove item from cart. Please try again in sometime.'
    end

    flash.keep
    redirect_to request.referer
  end
end

app/views/carts/show.html.erb
<div class="cart">
  <div class="cart_navs">
    <% if user_signed_in? %>
      <%= link_to "Proceed to checkout", new_order_path(current_user), class: 'btn btn-success' %>
    <% end %>
  </div>

  <h3>Cart Items</h3>

  <table class="list_cart_items table table-bordered tablesorter">
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr id="cart_item-<%= product.id %>" class="cart_item">
          <td>
            <%= link_to product.name, product_path(product) %>
          </td>
          <td>
            <%= number_with_delimiter(product.price, locale: :en) %> INR
          </td>
          <td>
            <%= product.quantity.to_i %>
          </td>
          <td>
            <%= number_with_delimiter((product.price * product.quantity), locale: :en) %> INR
          </td>
          <td>
            <%= link_to "Remove from cart", remove_item_path(product_id: product.id) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @products.count > 1 %>
    <table class="sub_list_cart_items table">
      <tbody>
        <tr>
          <td></td><td></td><td></td><td></td>
          <td>
            <b>Grand Total</b>
          </td>
          <td>
            <%= number_with_delimiter(grand_total(@products), locale: :en) %> INR
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>