config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :admins
  devise_for :users

  get 'admins/dashboard' => 'dashboard#index', as: :dashboard

  resources :products

  get 'add_to_cart' => 'carts#create', as: :add_to_cart
  get 'users/cart' => 'carts#show', as: :show_cart
  get 'cart/remove_item' => 'carts#remove_item', as: :remove_item
  get 'users/:id/orders/new' => 'orders#new', as: :new_order
  get 'users/:id/orders/create' => 'orders#create', as: :order_confirmation
  get 'users/:id/orders/display' => 'orders#show', as: :order_summary

  get 'fetch_products' => 'home#load_products'

end

app/views/layouts/_flash_message.html.erb
<div class="flash_messages">
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecomm</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "layouts/flash_message", flash: flash %>

    <% if user_signed_in? %>
      <%= link_to content_tag(:h2, "Welcome to Ecomm!", class: "h_m"), root_path, title: "Home", style: "text-decoration: none;" %>
    <% elsif admin_signed_in? %>
      <%= link_to content_tag(:h2, "Welcome to Ecomm!", class: "h_m"), dashboard_path, title: "Home", style: "text-decoration: none;" %>
    <% else %>
      <%= link_to content_tag(:h2, "Welcome to Ecomm!", class: "h_m"), root_path, title: "Home", style: "text-decoration: none;" %>
    <% end %>

    <div class="m_navs">
      <% if user_signed_in? %>
        <span class="wl_m">Welcome, <%= current_user.first_name %>!</span> |
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> |
        <% if @count_of_cart_items == 0 %>
          <span class="u_crt">My Cart (<%= @count_of_cart_items %>)</span>
        <% else %>
          <%= link_to content_tag(:span, "My Cart (#{@count_of_cart_items})", class: "u_crt"), show_cart_path %>
        <% end %>
      <% elsif admin_signed_in? %>
        <span class="wl_m">Welcome, <%= current_admin.first_name %>!</span> |
        <%= link_to "Sign Out", destroy_admin_session_path, method: :delete %>
      <% else %>
        <% unless (current_page?(new_user_session_path) || current_page?(new_admin_session_path) || current_page?(new_admin_registration_path)) %>
          <%= link_to "Login", new_user_session_path %> |
          <% if @count_of_cart_items == 0 %>
            <span class="u_crt">My Cart (<%= @count_of_cart_items %>)</span>
          <% else %>
            <%= link_to content_tag(:span, "My Cart (#{@count_of_cart_items})", class: "u_crt"), show_cart_path %>
          <% end %>
        <% else %>
          <%= link_to "Go To Home", root_path %>
        <% end %>
      <% end %>
    </div>

    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>